apiVersion: v1
kind: Secret
metadata:
  name: study-platform-secrets
  namespace: study-platform
  labels:
    app: study-platform
type: Opaque
data:
  
  # MongoDB Credentials
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # admin
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # password 
  
  # MongoDB URI (admin:password@mongodb-service:27017/studyplatform?authSource=admin)
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9zdHVkeXBsYXRmb3JtP2F1dGhTb3VyY2U9YWRtaW4=
  
  # JWT Secret 
  JWT_SECRET: bXktc3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLXN0dWR5LXBsYXRmb3JtLWRldmVsb3BtZW50
  
  # NVIDIA API Key 
  NVIDIA_API_KEY: "add your own key here and base64 encode it"
